//
//  13.2 异常处理中的返回.swift
//  算法
//
//  Created by Plum on 2021/6/3.
//  Copyright © 2021 Plum. All rights reserved.
//

import Foundation

/**
 * P363
 * 
 * 13.2 异常的返回，在Java中，如果try-catch-finally 中调用return, finally还会调用吗？
 * 会的
 * 除非：
 * 1.虚拟机退出
 * 2. 线程被杀死
 *
 */
